# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh github_package hadley/testthat
  - ./travis-tool.sh install_deps

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

env:
  - global:
    - WARNINGS_ARE_ERRORS=1
    - _R_CHECK_FORCE_SUGGESTS_=0
  - secure: lMtjG8MPD9VBxv3GqMlCCZf6sDPrPBt/SbfRgEnAtXA8n3aV7g/q/v2bQ6L8A1zEpusYfpiQFilQfHmsS8jSv21UdMe4Nu4nUhZxJBweuOpxF6PaiwwZGbGFrWQDOUH2MMZRJqceeE+mm5iSLrD/tlUTGFIDA8FHPWemz7JQ1Fw=


notifications:
  email:
    on_success: never
    on_failure: always
