# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh github_package hadley/testthat
  - ./travis-tool.sh install_deps

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

env:
  - global:
    - secure: "rQZjBh2BF0OO2HcR754iV0EVcoavysMp90uVRsHl6/3842XQP/Lpz5U+4deg8antntj8mDpIH/i8r2CRfzj99/zUaSbINCUB7pQhVzF7Lf/x9v6vG4siUWdtRiljCQLQRXD5qLrCNoTwNGKcoRizApWQUjMZ2ADRNuluUettKt8="
    - WARNINGS_ARE_ERRORS=1
    - _R_CHECK_FORCE_SUGGESTS_=0

notifications:
  email:
    on_success: never
    on_failure: always
